# Generated by Django 4.1 on 2022-09-24 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("tag", models.CharField(max_length=256)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("content", models.TextField()),
                ("content_html", models.TextField(editable=False)),
            ],
            options={"ordering": ["-create_time"],},
        ),
    ]
