# Generated by Django 4.1 on 2022-09-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="blog", unique_together=set(),),
    ]
