# Generated by Django 4.1 on 2022-09-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="publish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
