# Generated by Django 4.1 on 2022-09-25 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_approve_comments_blog_modify_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="modify_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
